version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tweetRawDataTopic:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  sampleservice:
    build:
      context: .
      dockerfile: SampleService/Dockerfile
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
  processservice:
    build:
      context: .
      dockerfile: ProcessService/Dockerfile
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
  #jhaconsole:
  #  build:
  #    context: .
  #    dockerfile: JHAConsole/Dockerfile
  #  depends_on:
  #    - kafka
  #  environment:
  #    - BOOTSTRAP_SERVERS=kafka:29092